#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

# Note: can directly use run-timit-test-common since it lives at the same level
# in the directory hierarchy.
. $TEST_DIR/../../../../Examples/Speech/TIMIT/run-timit-test-common

cntkrun TIMIT_TrainAutoEncoder.cntk "TIMIT_TrainAutoEncoder=[reader=[readerType=ExperimentalHTKMLFReader]]  $CntkArguments" || exit $?
