#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

# Note: can directly use run-timit-test-common since it lives at the same level
# in the directory hierarchy.
. $TEST_DIR/../../../../Examples/Speech/TIMIT/run-timit-test-common

# Running only 3 epochs (~1000s gpu release), because full run takes a lot of time.
cntkrun TIMIT_TrainLSTM.cntk "$CntkArguments TIMIT_TrainLSTM=[cvReader=[readerType=ExperimentalHTKMLFReader]] TIMIT_TrainLSTM=[reader=[readerType=ExperimentalHTKMLFReader]] TIMIT_TrainLSTM=[SGD=[maxEpochs=3]]" || exit $?
