#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

# Note: can directly use run-timit-test-common since it lives at the same level
# in the directory hierarchy.
. $TEST_DIR/../../../../Examples/Speech/TIMIT/run-timit-test-common

cntkrun TIMIT_TrainNDLNetwork.cntk "TIMIT_TrainNDL=[reader=[readerType=ExperimentalHTKMLFReader]] $CntkArguments" || exit $?
